### ISSUE TITLE
Опечатка в первом примере 

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-2#10]
Правило: `FORM.INPUT_AND_LABEL_SIZES_SHOULD_BE_EQUAL`
В примере указан json с такой строкой: `"content" [`
Насколько я понял из трансляции по вопросам, ошибки `json` валидировать не нужно и видимо это всё-таки опечатка.

**Comment by yndx-shri-reviewer** [comment]
Спасибо, поправили
