### ISSUE TITLE
Валидация отступов

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-2#11]
```
2. Вертикальный внутренний отступ контентного элемента формы content должен
задаваться с помощью микса на него элемента формы item со значением
модификатора space-v на 2 шага больше эталонного размера (например,
для размера l таким значением будет xxl).
```

1. Где можно взять список возможных размеров текста?
2. Что делать если такого размера не существует? 
Допустим эталонный размер текста `xxl` (если я правильно понимаю, что это максимальный размер). Тогда отступ не может быть валидным вообще и это не проблема контентного элемента.

**Comment by yndx-shri-reviewer** [comment]
1. В описании блока text https://github.com/yndx-shri-reviewer/task-1/blob/master/BASE.md#text
2. Для размера  текста  xxl  значение модификатора space-v должно быть xxxxl, в первом задании недоработка  в  описании  тут https://github.com/yndx-shri-reviewer/task-1/blob/master/BASE.md#элемент-item (забыли  указать это  значение  в  модификаторах), мы это поправим в ближайшее  время

**Comment by WIVSW** [comment]
> 1. В описании блока text https://github.com/yndx-shri-reviewer/task-1/blob/master/BASE.md#text
> 2. Для размера  текста  xxl  значение модификатора space-v должно быть xxxxl, в первом задании недоработка  в  описании  тут [https://github.com/yndx-shri-reviewer/task-1/blob/master/BASE.md#элемент-item](https://github.com/yndx-shri-reviewer/task-1/blob/master/BASE.md#%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82-item) (забыли  указать это  значение  в  модификаторах), мы это поправим в ближайшее  время

А не должна ли появится ошибка формы 1, если у текстового блока не правильный размер например:
```
{
    "block": "form",
    "content": {
        "block": "text",
        "mods": { 
            "size": "xxxl"
        }
    }
}
```
Или такой кейс не нужно обрабатывать?

**Comment by yndx-shri-reviewer** [comment]
Этот кейс обрабатывать не обязательно
