### ISSUE TITLE
Вычисление эталонного размера

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-2#12]
`Эталонным считается размер первого элемента формы.`

Не совсем ясны критерии по которым можно сказать, что размер является эталонным.
1. Правильно ли я понимаю, что эталонным размером может быть только `label` или `input`?
```
[
         {
            "block": "form",
            "elem": "label",
            "content": {
                "block": "text",
                "mods": { "size": "l" }
            }
        },
        { "block": "input", "mods": { "size": "l" } }
]
```
2. Правильно ли я понимаю, что в этом примере нет эталонного размера и элемент `.form__header` валиден?
```
{
    "block": "form",
    "content": [
        {
            "block": "form",
            "elem": "header",
            "content": {
                {
                    "block": "text",
                    "mods": {
                        "size": "xl"
                    }
                }
            ]
        }
    },
    {
        "block": "input",
        "mods": {
            "size": "l"
        }
    }
}
```

**Comment by yndx-shri-reviewer** [comment]
1. Эталонный размер задают элемент label блока form, а также блоки input и button. Они все в форме должны быть одного размера, если это не так - эталонным считается размер первого встретившегося из них. Поправим описание задание, там не очень понятно написано.
2. Здесь эталонный размер -  l

**Comment by WIVSW** [comment]
> 1. Эталонный размер задают элемент label блока form, а также блоки input и button. Они все в форме должны быть одного размера, если это не так - эталонным считается размер первого встретившегося из них. Поправим описание задание, там не очень понятно написано.
> 2. Здесь эталонный размер -  l

Спасибо за ответ! Извините, но я случайно предоставил не валидный `json`. И хотел бы на всякий случай уточнить: Правильно ли я понимаю, что в примере где есть, блок `form`, но у него нет ни `label`, ни `input`, ни `button`, то тогда эталонной размер необходимо искать на уровень выше?
```
[
	{
		"block": "form",
		"content": [
			{
				"block": "form",
				"elem": "header",
				"content": [
					{
						"block": "text",
						"mods": {
							"size": "xl"
						}
					}
				]
			}
		]
	},
        // Элемент формы закончился
	{
		"block": "button",
		"mods": {
			"size": "l" // Эталонный размер?
		}
	}
]
```

**Comment by yndx-shri-reviewer** [comment]
В этом случае эталонный размер не  определен, блок формы не  должен знать ни о чем снаружи. Нужно вернуть ошибку 1 правила

**Comment by bo4arovpavel1989** [comment]
> В этом случае эталонный размер не определен, блок формы не должен знать ни о чем снаружи. Нужно вернуть ошибку 1 правила

а если эталонный размер не определен, но присутствуют элементы (хедер. контен, футер), которые валидируются на его основе, по этим элементам линтер тоже должен выдавать ошибки?

**Comment by yndx-shri-reviewer** [comment]
поправили описание 1 правила, чтобы не возникало вопросов
