### ISSUE TITLE
Правило формы 5 и 9: Текстовые блоки

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-2#14]
Под текстовыми блоками в этом задании понимаются:
```
{
    "block": "text",
    "mods": {
        "size": "xxl"
    }
}
```
Или это могут быть еще и `label`, `input`, `button`?

**Comment by yndx-shri-reviewer** [comment]
Да, тут имеется  ввиду  именно { "block": "text" }
