### ISSUE TITLE
Правило последовательности заголовков

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-2#15]
Должно ли учитываться правило последовательности заголовков h2 и h3 для заголовков,  располагающихся на разных ветвях? Будут ли по этому правилу валидны заголовки ниже?
 `
{
  "block":"tree",
  "content":[

    {"block":"text", "mods":{"type":"h1"}},
    {"block":"branch1",
      "content":[
        {"block":"text", "mods":{"type":"h2"}},
        {"block":"text","mods":{"type":"h3"}}
      ]
    },
    {"block":"branch2",
      "content":[
        {"block":"text","mods":{"type":"h2"}},
        {"block":"text","mods":{"type":"h3"}}
      ]
    }
  ]
}
`

**Comment by yndx-shri-reviewer** [comment]
В  указанном примере заголовки будут валидны

**Comment by bo4arovpavel1989** [comment]
Еще момент, оно вроде и понятно, но на всякий случай уточню, правило "Заголовок третьего уровня (блок text с модификатором type h3) не может следовать перед заголовком второго уровня на одном или более глубоком уровне вложенности." Заголовок третьего уровня ведь не может стоять перед заголовком не только второго, но и первого уровня?

**Comment by yndx-shri-reviewer** [comment]
да, все верно

**Comment by bo4arovpavel1989** [comment]
Можно тогда вдогонку еще уточнение. Ниже правильно указана ошибка последовательности заголовков?
`{
"block":"tree",
"content":[

{"block":"text", "mods":{"type":"h1"}},
{"block":"branch1",
  "content":[
    {"block":"text", "mods":{"type":"h2"}},
    {"block":"text","mods":{"type":"h3"}},
   // Блок h3 на более глубоком уровне, но на этой ветви ошибки не будет
    {"block":"wrapper","content":{"block":"text","mods":{"type":"h3"}}}
  ]
},
{"block":"branch2",
  "content":[
   // Блок h3 следует перед h2 на более глубоком уровне - ошибка
    {"block":"wrapper","content":{"block":"text","mods":{"type":"h3"}}},
    {"block":"text","mods":{"type":"h2"}},
    {"block":"text","mods":{"type":"h3"}}
  ]
}
]
}`
правильно я понял, что имеется в виду на более глубоком уровне находится именно младший блок?

**Comment by yndx-shri-reviewer** [comment]
Да, комментарии в примерах выше верны
