### ISSUE TITLE
Элементы форм - content, header, footer

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-2#16]
В примерах на правила линтинга элементов форм приведено, что в дереве json эти элементы задаются явно, в реальных условиях они могут задаваться миксами, как например в блоке payment - элементы header и пр. - задаются именно как элементы именно блока payment, а не form. В этом задании, проходя по структурному дереву блока form, нужно иметь в виду, что эти элементы могут быть в виде миксов?

**Comment by yndx-shri-reviewer** [comment]
Задание через миксы равнозначно заданию "явно" и тоже должно учитываться. Нужно обратить внимание, что линтер валидирует именно блок form и его элементы. Элементы блока payment он не валидирует.

**Comment by bo4arovpavel1989** [comment]
Но ведь блок payment по спецификации миксуется с блоком form, а поскольку задание через миксы равнозначно заданию явно, то линтер начинает валидировать и его, разве нет?

**Comment by yndx-shri-reviewer** [comment]
задача - провалидировать блок формы и его элементы
