### ISSUE TITLE
Наличие размерного модификатора в форме

### ISSUE THREAD

**Issue by kaban270790** [yndx-shri-reviewer/task-2#17]
Может ли быть ситуация когда у лебла/инпута/кнопки нет размерного модификатора? Нужно ли это проверять и если да, то какую ошибку выкидывать?

**Comment by yndx-shri-reviewer** [comment]
Может, проверять нужно, это описано в 1 правиле:

> Все инпуты, кнопки и тексты в лейблах в блоке формы должны быть одного размера (c одинаковым значением модификатора size) и этот размер должен быть определен.
