### ISSUE TITLE
Подсчет location в примере

### ISSUE THREAD

**Issue by Tauka** [yndx-shri-reviewer/task-2#19]
В секции описания "Формат входных и выходных данных", дан такой пример ошибки
```

[
    {
        "code": "FORM.INPUT_AND_LABEL_SIZES_SHOULD_BE_EQUAL",
        "error": "Подписи и поля в форме должны быть одного размера",
        "location": {
            "start": { "column": 1, "line": 1 },
            "end": { "column": 2, "line": 17 }
        }
    }
]
```

Откуда взялся `column: 2` в `end`? Если `column` это позиция символа в строке, то ведь должно быть `column: 1` для `end`?

**Comment by yndx-shri-reviewer** [comment]
Начало  ошибки перед скобкой,  окончание за скобкой, в примере нет ошибки

**Comment by Tauka** [comment]
> Начало ошибки перед скобкой, окончание за скобкой, в примере нет ошибки

То есть предполагается что до и после скобок есть невидимые символы?

**Comment by kaban270790** [comment]
> То есть предполагается что до и после скобок есть невидимые символы?

Начальный и конечный символ - включительно, нумерация начинается с единицы. Я так понял

**Comment by Tauka** [comment]
> > То есть предполагается что до и после скобок есть невидимые символы?
> 
> Начальный и конечный символ - включительно, нумерация начинается с единицы. Я так понял

Не очень понимаю, то есть вот эти бэктики за скобками тоже считаются за символы? Я предполагал что символы это содержимое строки. Соотвественно, я вижу только один символ на 17 строке, закрывающую фигурную скобку

```javascript
const json = `{
    "block": "form",
    "content": [
        {
            "block": "form",
            "elem": "label",
            "content": {
                "block": "text",
                "mods": { "size": "xl" }
            }
        },
        {
            "block": "input",
            "mods": { "size": "xxl" }
        }
    ]
}`;
```

**Comment by yndx-shri-reviewer** [comment]
Попробуй  вставить этот json в webstorm и посмотреть на информацию о позициях символов там, чтобы понять механику. Информация в location будет использоваться для  подчеркивания некорректного участка в редакторе.
