### ISSUE TITLE
Опечатки в результатах автотестов

### ISSUE THREAD

**Issue by kaban270790** [yndx-shri-reviewer/task-2#20]
Обратил внимание на текст, очень сомневаюсь что так задумывалось =))

![image](https://user-images.githubusercontent.com/27147261/60667405-23776b80-9e72-11e9-95a2-2ecb5bd8046e.png)

**Comment by dima117** [comment]
Можете написать подробнее, что не так?

**Comment by kaban270790** [comment]
@dima117 извиняюсь, не правильно сопоставил смысл текст и значка
