### ISSUE TITLE
Валидация заголовков: вложенность и порядок

### ISSUE THREAD

**Issue by chrstnv** [yndx-shri-reviewer/task-2#21]
Подскажите, пожалуйста, валидна ли ситуация, когда сначала идет вложенный h2, а затем вложенный h1 (по аналогии вопрос с h2 и h3)?

Например, такая структура:
```
{
  "block":"block1",
  "content":[
    {
      "block":"block2",
      "content":{
        "block":"block3",
        "content":{
          "block":"text",
          "mods":{
            "size":"xl",
            "type":"h2"
          }
        }
      }
    },
    {
      "block":"block4",
      "content":{
        "block":"text",
        "mods":{
          "type":"h1"
        }
      }
    }
  ]
}
```

В этом issue задавали связанный вопрос, но все-таки пример немного другой: https://github.com/yndx-shri-reviewer/task-2/issues/15

**Comment by NazarkinRoman** [comment]
up. тоже хотелось бы уточнить.
