### ISSUE TITLE
Валидация заголовков: вложенность и порядок [2]

### ISSUE THREAD

**Issue by NazarkinRoman** [yndx-shri-reviewer/task-2#23]
Не так давно здесь был issue #21 по этому поводу, но автор закрыл его без ответа. Собственно, вопрос тот же. Дублирую здесь.

> Подскажите, пожалуйста, валидна ли ситуация, когда сначала идет вложенный h2, а затем вложенный h1 (по аналогии вопрос с h2 и h3)?

Структура:
```
{
  "block":"block1",
  "content":[
    {
      "block":"block2",
      "content":{
        "block":"block3",
        "content":{
          "block":"text",
          "mods":{
            "size":"xl",
            "type":"h2"
          }
        }
      }
    },
    {
      "block":"block4",
      "content":{
        "block":"text",
        "mods":{
          "type":"h1"
        }
      }
    }
  ]
}
```

Будет ли это валидным кодом?

**Comment by chrstnv** [comment]
Как автор, закрывший issue без ответа, могу подсказать, что мой код такой кейс не учитывает, и автотесты прошли :) Надеюсь, после этого комментария новых автотестов не прибавится 😅

**Comment by NazarkinRoman** [comment]
@chrstnv не учитывает = не генерирует ошибку?

**Comment by chrstnv** [comment]
Ага, у меня такой кейс считается валидным.

**Comment by NazarkinRoman** [comment]
@chrstnv просто у меня вообще ни один автотест по заголовкам не проходит и это странно. если в случае со вторым и третьим правилами могут быть какие-то разночтения, то первое правило максимально простое - в нем ошибок не должно быть. (возможно, автотесты его не проверяют вообще?)

**Comment by chrstnv** [comment]
Возможно, тесты падают где-то в начале проверки по какой-то причине и просто дальше не идут. Соответственно, количество пройденных тестов маленькое. У меня так было, починила глупый TypeError и сразу прошло большое количество тестов.

**Comment by danilstoyanov** [comment]
Товарищи, маленький оффтопик, но всё же есть один вопрос
У вас получилось тесты в первом задании пройти?
Если получилось, то функцию шаблонизации просто экспортируете как:
```
export default function(bemJson) { ... }
```
?

**Comment by chrstnv** [comment]
Я экспортирую именно так (так в задании написано), но пока ни одного теста не прошла :(

**Comment by NazarkinRoman** [comment]
@danilstoyanov пока не прошел тесты тоже. Но да, функция экспортируется так.

**Comment by danilstoyanov** [comment]
@chrstnv https://github.com/yndx-shri-reviewer/task-1/issues/60
Вот тут тредик есть, можно следить за обновлениями. Как написал проверяющий, шаблонизатор сделанный @NazarkinRoman запускается, просто из-за несоответствий в стилях не проходит тест

**Comment by NazarkinRoman** [comment]
@danilstoyanov ну тут для честности стоит сказать, что у меня файл тот через webpack сначала проходит, поэтому код, который непосредственно попадает в автотест, использует другие конструкции экспорта.

**Comment by danilstoyanov** [comment]
@NazarkinRoman вобщем, надеюсь что на днях добавят логи из консоли, чтобы те кто фейлят успели принять меры)

**Comment by NazarkinRoman** [comment]
@danilstoyanov на самом деле, логи и в этом задании не помешали бы (прозрачный намек в сторону @yndx-shri-reviewer) ведь если действительно на каком-то из тестов линтер падает, то сидеть и гадать из-за чего же это - такая себе идея :)

**Comment by danilstoyanov** [comment]
@NazarkinRoman согласен, поддержку пальцем вверх)

**Comment by SkyFlame00** [comment]
> @danilstoyanov ну тут для честности стоит сказать, что у меня файл тот через webpack сначала проходит, поэтому код, который непосредственно попадает в автотест, использует другие конструкции экспорта.

Но ведь предполагается, что исходник `template-engine.js` должен содержать именно ES6 export? То есть `module.exports` из CommonJS не подойдет

**Comment by danilstoyanov** [comment]
@SkyFlame00 угу, я вот стараюсь на второе задание переключиться, чтобы не терзаться размышлениями и догадками :D

**Comment by SkyFlame00** [comment]
> @SkyFlame00 угу, я вот стараюсь на второе задание переключиться, чтобы не терзаться размышлениями и догадками :D

Да, согласен. Я уже несколько дней как к первому не возвращался.

**Comment by SkyFlame00** [comment]
> Не так давно здесь был issue #21 по этому поводу, но автор закрыл его без ответа. Собственно, вопрос тот же. Дублирую здесь.
> 
> > Подскажите, пожалуйста, валидна ли ситуация, когда сначала идет вложенный h2, а затем вложенный h1 (по аналогии вопрос с h2 и h3)?
> 
> Структура:
> 
> ```
> {
>   "block":"block1",
>   "content":[
>     {
>       "block":"block2",
>       "content":{
>         "block":"block3",
>         "content":{
>           "block":"text",
>           "mods":{
>             "size":"xl",
>             "type":"h2"
>           }
>         }
>       }
>     },
>     {
>       "block":"block4",
>       "content":{
>         "block":"text",
>         "mods":{
>           "type":"h1"
>         }
>       }
>     }
>   ]
> }
> ```
> 
> Будет ли это валидным кодом?

То есть если заголовки находятся в разных ветках, то ок?

**Comment by NazarkinRoman** [comment]
@SkyFlame00 вот как раз и не понятно - ок или не ок

**Comment by danilstoyanov** [comment]
Порядок заголовков это единственный критерий, по которому я тесты в этом задании прохожу все тесты правильно (их 8). Конкретно данный случай я не учитывал (хотя возможно стоит).

**Comment by NazarkinRoman** [comment]
> > @danilstoyanov ну тут для честности стоит сказать, что у меня файл тот через webpack сначала проходит, поэтому код, который непосредственно попадает в автотест, использует другие конструкции экспорта.
> 
> Но ведь предполагается, что исходник `template-engine.js` должен содержать именно ES6 export? То есть `module.exports` из CommonJS не подойдет, или что там вебпак использует D:

Так ведь вебпак работает одновременно и с тем и с тем, поэтому в сущности не важно как будет написан экспорт

**Comment by SkyFlame00** [comment]
Ну да, [тут](https://github.com/yndx-shri-reviewer/task-2/issues/15) про ветки как раз сказано.

**Comment by chrstnv** [comment]
Резюме – выходит, кейс валидный, обрабатывать не требуется. Ура.

**Comment by NazarkinRoman** [comment]
@SkyFlame00 @chrstnv тот issue немного о другом и там не рассматривался случай, приведённый здесь. Поэтому хотелось бы услышать окончательный ответ от представителей ШРИ.

**Comment by yndx-shri-reviewer** [comment]
Структура из первого комментария будет валидна, так как заголовки находятся в разных ветвях дерева.

**Comment by yndx-shri-reviewer** [comment]
> @danilstoyanov на самом деле, логи и в этом задании не помешали бы (прозрачный намек в сторону @yndx-shri-reviewer) ведь если действительно на каком-то из тестов линтер падает, то сидеть и гадать из-за чего же это - такая себе идея :)

Попробуйте написать свой вариант тестов на код - это поможет найти ошибки и будет плюсом при оценке тестового задания
