### ISSUE TITLE
Какие правила не проходят?

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-2#24]
У меня такая ситуация с тестами. Можно ли узнать, с какими правилами мой линтер не справляется? Не могу найти ошибки.

![Безымянный](https://user-images.githubusercontent.com/7037108/61210114-2c82fb00-a704-11e9-89c2-69a42c1989b0.png)

**Comment by danilstoyanov** [comment]
Присоединяюсь, уже написал в поддержку письмо, вдруг что с тестами не так?
Уже какие-только краевые случаи не рассматривал, всё равно не получается :(
![image](https://user-images.githubusercontent.com/18240896/61210800-48879c00-a706-11e9-870d-2e2258e79291.png)

**Comment by bo4arovpavel1989** [comment]
> 
> 
> Присоединяюсь, уже написал в поддержку письмо, вдруг что с тестами не так?
> Уже какие-только краевые случаи не рассматривал, всё равно не получается :(
> ![image](https://user-images.githubusercontent.com/18240896/61210800-48879c00-a706-11e9-870d-2e2258e79291.png)

Хех, у меня наоборот - блок form валидируется полностью, а 2 теста валидации заголовков не проходят

**Comment by danilstoyanov** [comment]
@bo4arovpavel1989 кстати!
Я тоже мог добиться такого эффекта)

**Comment by danilstoyanov** [comment]
@bo4arovpavel1989 в одной из версий кода. Но решил этот вариант оставить, т.к. тут всего лишь один тест падает)

**Comment by SkyFlame00** [comment]
@danilstoyanov в поддержку это куда писать?

**Comment by danilstoyanov** [comment]
@SkyFlame00 я писал по адресу: frontendschool@yandex-team.ru
Письмо вчера утром написал, пока что жду ответа.

**Comment by chrstnv** [comment]
@danilstoyanov  попробуй проверить кейс, когда для формы не удалось определить эталонный размер (нет ни одного элемента-лейбла, инпута или кнопки с заданным размером). Линтер должен выдавать ошибку. Когда я такую проверку сделала, у меня ровно один пройденный тест прибавился :)

**Comment by danilstoyanov** [comment]
> @danilstoyanov попробуй проверить кейс, когда для формы не удалось определить эталонный размер (нет ни одного элемента-лейбла, инпута или кнопки с заданным размером). Линтер должен выдавать ошибку. Когда я такую проверку сделала, у меня ровно один пройденный тест прибавился :)

Этот кейс я проверял, если эталонного размера нет то возвращаю ошибку 1 правила. Но пожалуй нужно перепроверить, спасибо!

**Comment by yndx-shri-reviewer** [comment]
Мы не открываем тесты, которые проверяют правильность выполненного задания.
Общий совет такой:
- Еще раз перечитать задание  и уточнить все ли  правила учтены
- Написать свои тесты для проверки вашего  кода - это действительно поможет найти большинство ошибок
- Обратить внимание на  обработку  краевых случаев
- Перечитать вопросы в соседних issues и ответы на  них
