### ISSUE TITLE
Пустой эталонный размер

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-2#25]
Если первый встреченный из label (точнее, text, лежащий внутри него), input или button имеет модификатор `size: ''`, то как это должно обрабатываться? Линтер должен дойти до такого следующего label, input или button, у которого модификатор size будет непустой и сделать уже его эталонным?

**Comment by danilstoyanov** [comment]
> Если первый встреченный из label (точнее, text, лежащий внутри него), input или button имеет модификатор `size: ''`, то как это должно обрабатываться? Линтер должен дойти до такого следующего label, input или button, у которого модификатор size будет непустой и сделать уже его эталонным?

Хм, любопытный кейс. Я просто чекал возможность отсутствия у элемента модификатора size полностью и если он отсутствовал, то далее искал подходящий элемент.

Но интересно, что скажут организаторы, для 100% уверенности.

**Comment by SkyFlame00** [comment]
@danilstoyanov ну вот это сюда же: как обрабатывать случай, если у label, input или button модификатора совсем не будет либо он будет равен null или undefined?

**Comment by danilstoyanov** [comment]
> @danilstoyanov ну вот это сюда же: как обрабатывать случай, если у label, input или button модификатора совсем не будет либо он будет равен null или undefined?

Скорее всего, обходить дерево дальше, когда будет найден эталонный размер.
Также, при сравнении размеров элементов в дальнейшем выкидывать ошибку 1 правила, когда будет сравниваться размер элемента со сломанным модификатором с эталонным размером.

Ведь ```' ' | null | undefined``` никак не смогут быть нормально сравнены с эталонным размером.

**Comment by SkyFlame00** [comment]
Эту issue #17 как-то пропустил
