### ISSUE TITLE
Вопрос по первому правилу

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-2#27]
Для такого json линтер должен выдавать 3 ошибки правила 1 (в форме не определен эталонный размер и оба инпута невалидны)?

```
{
  "block": "form",
  "content": [
    {
      "block": "input",
      "mods": { "size": "" }
    },
    {
      "block": "input",
      "mods": { "size": "" }
    }
  ]
}
```

**Comment by bo4arovpavel1989** [comment]
Тут будет 1 ошибка, поскольку она относится целиком к блоку form

**Comment by SkyFlame00** [comment]
@bo4arovpavel1989 тогда если у нас в форме несколько элементов из label, input или button не соответствуют эталонному размеру, то выводится только 1 ошибка? Вообще, логично, конечно, раз мы навешиваем ошибку на всю форму, но это резко контрастирует со всеми остальными правилами.

**Comment by VladislavYeremeyev** [comment]
> @bo4arovpavel1989 тогда если у нас в форме несколько элементов из label, input или button не соответствуют эталонному размеру, то выводится только 1 ошибка? Вообще, логично, конечно, раз мы навешиваем ошибку на всю форму, но это резко контрастирует со всеми остальными правилами.

Предполагаю, что если элемент не соответствует эталонному значению (при этом эталонное значение существует), тогда каждый такой ошибочный элемент генерирует по ошибке.

Если же эталон не определен, то будет одна ошибка.

**Comment by bo4arovpavel1989** [comment]
> > @bo4arovpavel1989 тогда если у нас в форме несколько элементов из label, input или button не соответствуют эталонному размеру, то выводится только 1 ошибка? Вообще, логично, конечно, раз мы навешиваем ошибку на всю форму, но это резко контрастирует со всеми остальными правилами.
> 
> Предполагаю, что если элемент не соответствует эталонному значению (при этом эталонное значение существует), тогда каждый такой ошибочный элемент генерирует по ошибке.
> 
> Если же эталон не определен, то будет одна ошибка.

Ориентируясь на то, что у меня тесты по валидацию блока form проходят все, могу сказать, что в любом случае ошибка выдается только одна на весь блок. Да, это и будет выглядеть бессмысленно - несколько одинаковых ошибок, т.к. там везде будет один и тот же код и один и тот же location блока form

**Comment by SkyFlame00** [comment]
Да, оказывается, в одной из версий кода у меня этот кейс был ненароком учтен. 1 ошибка, если эталон не задан, и произвольное количество, если задан
