### ISSUE TITLE
Правило заголовков №3

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-2#29]
Как должна обрабатываться последовательность h3 - h2 - h1? Поскольку h3 не может стоять до h1 и h2, должны ли в массив добавляться две одинаковые ошибки правила №3?

```
{
  "block": "root",
  "content": [
    {
      "block": "text",
      "mods": { "type": "h3" }
    },
    {
      "block": "text",
      "mods": { "type": "h2" }
    },
    {
      "block": "text",
      "mods": { "type": "h1" }
    }
  ]
}
```

В итоге здесь должно быть 3 ошибки: две ошибки по правилу 3, одна ошибка по правилу 2? Или нет?

**Comment by yndx-shri-reviewer** [comment]
Ошибки должно быть 2 - по одной на каждое невыполненное правило
