### ISSUE TITLE
Поддержка массива в качестве корня

### ISSUE THREAD

**Issue by SkyFlame00** [yndx-shri-reviewer/task-2#31]
Никак не могу найти 2 ошибки в заголовках и 1 в форме. Дошло, что стоит добавить поддержку массива в качестве корня, поскольку заголовки в примерах как раз в массивах лежат:

```
[
  {
    "block": "text",
    "mods": { "type": "h3" }
  },
  {
    "block": "text",
    "mods": { "type": "h2" }
  }
]
```

Но не помогло, все так же 6 из 8.

Нужна ли вообще поддержка массива в качестве корня bemjson? И могут ли в корневом массиве лежать вложенные массивы? Типа такого:

```
[
  [
    {
      "block": "text",
      "mods": { "type": "h3" }
    }
  ],
  [
    {
      "block": "text",
      "mods": { "type": "h2" }
    }
  ]
]
```

**Comment by SkyFlame00** [comment]
У меня уже совсем идей нет, что еще можно проверить :(

Array: корень bemjson'а - массив. Not array: корень bemjson'а - какой-нибудь блок.

![2](https://user-images.githubusercontent.com/7037108/61530866-f60fed80-aa2d-11e9-9fc3-49ca3801a443.png)

**Comment by SkyFlame00** [comment]
Наконец-то удалось найти непроверенный кейс.

Я проверял это:

```
[
  {
    "block": "mock",
    "content": {
      "block": "text",
      "mods": { "type": "h2" }
    }
  },
  {
    "block": "text",
    "mods": { "type": "h1" }
  }
]
```

Но не проверял это:

```
[
  {
    "block": "text",
    "mods": { "type": "h2" }
  },
  {
    "block": "mock",
    "content": {
      "block": "text",
      "mods": { "type": "h1" }
    }
  }
]
```

**Comment by bo4arovpavel1989** [comment]
> Наконец-то удалось найти непроверенный кейс.
> 
> Я проверял это:
> 
> ```
> [
>   {
>     "block": "mock",
>     "content": {
>       "block": "text",
>       "mods": { "type": "h2" }
>     }
>   },
>   {
>     "block": "text",
>     "mods": { "type": "h1" }
>   }
> ]
> ```
> 
> Но не проверял это:
> 
> ```
> [
>   {
>     "block": "text",
>     "mods": { "type": "h2" }
>   },
>   {
>     "block": "mock",
>     "content": {
>       "block": "text",
>       "mods": { "type": "h1" }
>     }
>   }
> ]
> ```

А разве этот кейс должен выдавать ошибку? Здесь же блок h2 на менее глубоком уровне вложенности

**Comment by SkyFlame00** [comment]
@bo4arovpavel1989 да, такой кейс выдает ошибку. В данном случае они тоже находятся на одной ветке. h2 для h1 как бы "дядя"

**Comment by bo4arovpavel1989** [comment]
> @bo4arovpavel1989 да, такой кейс выдает ошибку. В данном случае они тоже находятся на одной ветке. h2 для h1 как бы "дядя"

Вообще странно, ведь в условиях сказано, что ошибка должна выдаваться, если младший блок на одном или более глубоком уровне вложенности, здесь же блок h2 на менее глубоком уровне. И после этого кейса все тесты прошли?

**Comment by SkyFlame00** [comment]
@bo4arovpavel1989 Да, не сказано. Судя по всему, нужно догадываться. В предыдущих issues они дали понять, что заголовки должны быть расположены правильно именно в пределах одной ветки. Какой-то из заголовков может быть вложен. Пришлось очень много времени убить, чтобы понять, что не так. Проверяйте, у вас должны пройти оставшиеся 2 автотеста

**Comment by bo4arovpavel1989** [comment]
@SkyFlame00 Спасибо большое, оставшиеся теперь прошли)))
