### ISSUE TITLE
Положение ошибочного блока

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-2#4]
Я правильно понимаю , что линтер должен указывать положение ошибочного блока целиком, а не конкретный блок/элемент внутри с ошибочными значениями? 
То есть у нас есть блок form, для которого заданы 9 правил, проверяющих элементы header, footer, content и пр., и в случае нахождения, например, ошибки в отступах в headere, линтер должен указать положение всего блока form или этого header-а?

**Comment by WIVSW** [comment]
У каждого правила свой блок для отображения, это написано рядом с кодом ошибки.

**Comment by bo4arovpavel1989** [comment]
Спасибо, теперь увидел
