### ISSUE TITLE
Чередование заголовков (h2 - h3 - h2) на одном уровне вложенности

### ISSUE THREAD

**Issue by vaiil** [yndx-shri-reviewer/task-2#6]
> Заголовок второго уровня (блок text с модификатором type h3) не может следовать перед заголовком второго уровня на одном или более глубоком уровне вложенности.
> 
> ```
>[
>     // неправильно
>     {
>         "block": "text",
>         "mods": { "type": "h3" }
>     },
>     {
>         "block": "text",
>         "mods": { "type": "h2" }
>     }
> ]
>```

Корректно ли при этом чередование заголовков на одном уровне вложенности? То есть:
```
[
    {
        "block": "text",
        "mods": { "type": "h2" }
    },
    {
        "block": "text",
        "mods": { "type": "h3" }
    },
    {
        "block": "text",
        "mods": { "type": "h2" }
    }
]
```

**Comment by yndx-shri-reviewer** [comment]
Нет, h3 никогда не может следовать перед  h2
