### ISSUE TITLE
Автотесты для отдельного задания

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-2#7]
Не уверен куда именно писать - напишу здесь.
Возможно ли как-то прогнать автотесты только для отдельного задания?
Тестировать сразу 2 задания не очень удобно, потому что потеряется контекст первой задачи, которую выполнял.

**Comment by yndx-shri-reviewer** [comment]
Да, можно просто выбрать пустые репозитории для остальных заданий
