### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by bo4arovpavel1989** [yndx-shri-reviewer/task-2#8]
по правилам BEMJSON mods будет проигнорирован если указаны elem и elemMods. В примерах указан в каждом form__item:      elem:item  и  mods: {...}. Я правильно понимаю, что mods игнорируется только если одновременно указываются elem и elemMods, а  в данном случае mods не должен игнорироваться? Или должно быть elem: item, elemMods:{}?

**Comment by yndx-shri-reviewer** [comment]
Все правильно, в данном случае mods не будет проигнорирован

**Comment by ValeraS** [comment]
> Все правильно, в данном случае mods не будет проигнорирован

`mods` в данном случае будут модификаторами блока или элемента?

Или все таки, `mods` должен быть проигнорирован, как это делает шаблонизатор `BEMHTML`
```js
{
    block: 'control',
    // Будет проигнорирован, так как указан elem
    mods: { type: 'nav' },
    elem: 'input'
}
```
```html
<div class="control__input"></div>
```
[Online demo](https://bem.github.io/bem-xjst/?version=8.9.1&engine=BEMHTML&template=%2F%2F%20Default%20tag%0A&bemjson=(%5B%0A%20%20%7B%0A%20%20%20%20block%3A%20%27control%27%2C%0A%20%20%20%20%2F%2F%20%D0%91%D1%83%D0%B4%D0%B5%D1%82%20%D0%BF%D1%80%D0%BE%D0%B8%D0%B3%D0%BD%D0%BE%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%2C%20%D1%82%D0%B0%D0%BA%20%D0%BA%D0%B0%D0%BA%20%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D1%8B%20elem%0A%20%20%20%20mods%3A%20%7B%20type%3A%20%27nav%27%20%7D%2C%0A%20%20%20%20elem%3A%20%27input%27%0A%7D%0A%5D)%3B%0A)

Мне кажется, корректнее было бы использовать `elemMods` в данном случае. Тем более в первом задании это поправили https://github.com/yndx-shri-reviewer/task-1/issues/4#issuecomment-504931942.

**Comment by yndx-shri-reviewer** [comment]
mods в данном случае будут модификаторами элемента. 
Вы правы, так было бы корректней использовать elemMods, но есть люди, которые  уже выполнили задание  с линтером и для них будет неожиданностью  то, что  условия задания  поменялись.
