### ISSUE TITLE
Изолированность автотестов

### ISSUE THREAD

**Issue by WIVSW** [yndx-shri-reviewer/task-2#9]
**Проблема:**
Запустил тесты для второго задания и получил сообщение о двух ошибках:
1. Не прошел тест валидации формы (что, к слову очень абстрактно т.к. там очень много кейсов для тестирования)
2. Не прошел тест на вычисление location блока

У меня в проекте написаны `unit`-тесты, в которых используется код, указанный в примерах к заданию. 
После получения результатов автотестов, я решил, что возможно ошибка в тестах и вручную пересчитал **ВСЕ** отступы для каждого из кейса из примеров. Оказалось, что тесты корректны и location для всех случаев которые есть в описании к задаче вычисляются правильно. 

Но ошибка все же есть. 

В самом решении `location` для всех блоков парсится одинаково и вероятность того, что для одного блока `location` вычисляется правильно, а для другого нет - не возможна, т.к. если бы ломалось бы вычисление для одного теста, то ломалось бы для всех. Если вам кажется, что я для всех тест кейсов, которые знаю захардкодил результаты - вы меня обижаете и у меня есть исходный код, который это может опровергнуть.

**Вопрос:**
Возможна ли ситуация, где тест кейсы для валидации формы и вычисления `location` могут пересекаться и из-за этого могут показываться 2 ошибки вместо одной?

Из-за отсутствия открытых тест-кейс очень тяжело локализовать проблему и сузить область поиска очень важно.

**Comment by yndx-shri-reviewer** [comment]
Если линтер не возвращает ошибку по какому-либо правилу, не сможет пройти и проверка на позицию ошибки этого правила.
Посмотрите в каких правилах при линтинге вы могли допустить ошибки, обратите внимание на обработку краевых случаев, возможно вам помогут ответы на вопросы в соседних issues

**Comment by WIVSW** [comment]
> Если линтер не возвращает ошибку по какому-либо правилу, не сможет пройти и проверка на позицию ошибки этого правила.
> Посмотрите в каких правилах при линтинге вы могли допустить ошибки, обратите внимание на обработку краевых случаев, возможно вам помогут ответы на вопросы в соседних issues

А возможно ли как-то увидеть процент не пройденных тестов? В ответах на issues, действительно, увидел, что не везде логика показа ошибки не сходится с моей. Произвел изменения, получил тот же самый и не понятно стало лучше или хуже.

**Comment by yndx-shri-reviewer** [comment]
Сделали информацию о количестве пройденных тестов.
